### ISSUE TITLE
Add support for corp repos

### ISSUE THREAD

**Issue by antrromet** [btkelly/gnag#128]
Can you add support for repos that are hosted on a corp account?

**Comment by btkelly** [comment]
This should be supported as of now. You just need to provide an `authToken` from an account that has read / write access to the repo in question.

We are also in the process of creating a Gnag Github Application that would allow you to give the application access to the corporate account in question without the need for an auth token from a different account. We will post links and update the README once this is ready.

**Comment by antrromet** [comment]
@btkelly But the repo, that I'm trying to integrate gnag in, exists only on our corp account. So in the gnag github configuration I give the `repoName` as `ABCMobile/ABCAndroid` and this particular repo exists only on `git.corp.ABC.com`. It doesn't exist on `github.com`.

**Comment by btkelly** [comment]
@antrromet Ah, alright I didn't understand at first. So this is a Github Enterprise account? Would the ability to change the GitHub root URL do the trick?

**Comment by antrromet** [comment]
Yes that'd work! So in that case, the gnag github configuration would look something like

```
github {
        repoUrl 'git.corp.abc.com/ABCMobile/ABCAndroid' //This will be the full url to the repo
        authToken 'xxxx'
    }
```

**Comment by btkelly** [comment]
@antrromet version 1.2.2 has been deployed and should have what you need to support corporate accounts. Check the updated README for implementation details. Let me know how it works out, I don't have access to a corporate account so I'm curious.

**Comment by antrromet** [comment]
So I upgraded gnag version to `1.2.2`. And my github config looks like this

```
github {
       rootUrl 'https://git.corp.ABC.com/'
       repoName 'ABCMobile/ABCAndroid'
       authToken 'xxxxx'
   }
```

and I ran the command 
`./gradlew clean gnagReport -PissueNumber=123 -PauthToken=xxxxx`

But it didn't report anything on the pr. Is there anything I can debug this to identify whats going wrong? The auth key has all the access so that should not be the problem. Anything I might wanna change or try?

**Comment by btkelly** [comment]
Are you sure that the issueNumber matches the PR number you are expecting it to post to? For instance `https://github.com/btkelly/gnag/pull/130` is number `130`.

**Comment by btkelly** [comment]
I'm wondering if it's because you have left off the `/repos/`part of the URL. I should probably update the code and not have that be part of the `rootUrl`. In the meantime, try setting your `rootUrl` to `https://git.corp.ABC.com/repos/`.

**Comment by antrromet** [comment]
The PR number is correct. And regarding the url I tried botht he following but in vain.
- https://git.corp.ABC.com/repos/
- https://git.corp.ABC.com/api/v3/repos/

Any other suggestions?
And I also double checked my auth key for permissions and its correct.

**Comment by antrromet** [comment]
Another thing to note is, earlier when I had missed the `/repos` part, there were logs printed in the console where I ran the gradle task. The logs were `Unknown Host exception`. But now with the above 2 urls I don't see that logs. So I assumed, that its hitting the right url but am not sure whats going wrong.
