### ISSUE TITLE
Describe how to apply Gnag to multiple Gradle subprojects

### ISSUE THREAD

**Issue by stkent** [btkelly/gnag#131]

**Comment by stkent** [comment]
I just did this on an internal project and it wasn't too bad; the only weird thing was Checkstyle configuration breaking in an obscure fashion because the path to my suppressions file was no longer accurate. Related: may be worth adding a troubleshooting section to help with obscure errors such as that one (describe a systematic way to resolve them).

**Comment by amatkivskiy** [comment]
any updates on this, guys?

**Comment by stkent** [comment]
I can have a go at writing up some documentation this weekend.
