### ISSUE TITLE
Fix GitHub capitalization in repo description

### ISSUE THREAD

**Issue by stkent** [btkelly/gnag#134]
> A Gradle plugin that helps facilitate Github PR checking and automatic commenting of violations.

should become (emphasis for clarity only):

> A Gradle plugin that helps facilitate **GitHub** PR checking and automatic commenting of violations.

**Comment by stkent** [comment]
@btkelly only you can handle this one!

**Comment by btkelly** [comment]
Only took 21 days!

**Comment by stkent** [comment]
![bitmoji](https://render.bitstrips.com/v2/cpanel/10079860-120874784_10-s1-v1.png?transparent=1&width=246)
