### ISSUE TITLE
gnagReport task doesn't fail build when issue found

### ISSUE THREAD

**Issue by amatkivskiy** [btkelly/gnag#140]
Hi guys,
Thanks for such a cool plugin. It is awesome. 👍 
Recently I found that `gnagReport` task doesn't fail when code issues are found.

**Environment:**
I have project with android library module and app module that uses it. 
When I am building the whole project I want to perform gnag check for a library module and then  build the whole projects with all modules.

Everything works as expected when I run ` ./gradlew gnagCheck build`. As there are issues in the code `gnagCheck` expectedly fails and the whole command also fails.

But when I run ` ./gradlew gnagReport build` the whole command does not fail.
I see gnag output
```
Checkstyle detected 0 violations.
PMD detected 0 violations.
Executing findbugs FindBugsTask from ant task
[ant:null] Java Result: 3
Findbugs detected 2 violations.
One or more violation detectors has found violations. Check the report at root/library/build/outputs/gnag/gnag.html for details.
:library:gnagReport
Project status: failure
```
and the command execution continues and task `build` is executed next.

On my opinion `gnagReport` task should also fail like `gnagCheck`. What do you think?

**Comment by btkelly** [comment]
This is actually on purpose. The build does not fail during compilation as it is unaware if there are other modules that need to be checked as well as needing to report all violations to GitHub. The plugin will collect all violations detected and use the [GitHub Status API](https://developer.github.com/v3/repos/statuses/) to report a failing status on each module in the PR. To enforce the Gnag status you can require that the Gnag status passes before allowing anyone to merge the PR in question which is basically the same as a failing build. More information on requiring a specific status can be found [here](https://help.github.com/articles/enabling-required-status-checks/). Hope that helps.

**Comment by stkent** [comment]
Yeah, Bryan nailed it. Perhaps we could add this clarification to the task docs or README so it's more visible? I agree it can be surprising when you first run into it.

**Comment by amatkivskiy** [comment]
Thanks @btkelly for explanation. Then it will be nice to have some kind of interceptor for the `gnagReport` task. 
For example:
Before the task started we can trigger a pending status for the github commit and after its successful run depending on the check trigger failure or success statuses.

**Comment by amatkivskiy** [comment]
@btkelly Thanks for clarification 👍
