### ISSUE TITLE
No gnag comments in PR after it was created

### ISSUE THREAD

**Issue by amatkivskiy** [btkelly/gnag#141]
Hi Guys,

Found that gnag won't post status check comments for the first commit in the branch (before PR being created). For this case gnag will run `gnagCheck` task as it is not in PR context. 
But I discovered that Github API allows to post single commit comments and statuses which later will be show as comments in PR.

So it will be nice to have task like 
```
gnagReport -PcommitSha=43f9fe4653838817eb455c8d9977098adc797b41
```
 which will report statuses and review comments for single commit.

**Comment by btkelly** [comment]
I'm not quite sure I follow. Can you explain a scenario where you would need to run `gnagReport` before creating a PR? And what do you mean "For this case gnag will run `gnagCheck`"? What script and / or CI system are you using to run your builds?

**Comment by amatkivskiy** [comment]
Sorry for confusion. 😞 

First of all, on the project where I use gnag I configured `gnag` status check as required for PR.

Usually I have the following flow:
1. I create local branch.
2. Commit all the required stuff locally.
3. Push this local branch to remote.
4. Create PR with changes that I made.

For such situations `gnag` doesn't post status checks to the target PR till you make the first commit **after** you created PR.

This is because in `travis-build.sh` we have configuration when `gnagReport` is run only when build is done in the PR context (by checking `if [ "${TRAVIS_PULL_REQUEST}" = "false" ];`)

My idea is to always run `gnagReprot` on the CI. If build is in PR context then use PR to post status checks. If not then run `gnagReport` with commit SHA. Github allows commenting and marking status for a single commit. 
On of the benefits of such flow is : when you lately create PR with that commit the status checks and comments will be transferred from that single commit to a PR. So there will be no need to run `gnagReport` in this PR to get a status check.

**Comment by btkelly** [comment]
This sounds like an interesting use case that I would expect to be quite rare. I would think you would run `gnagCheck` locally on a commit to make sure you are not violating any of the Gnag rules and once good you would commit and make a PR. In that case it would check and report on the PR when someone else is looking to merge. My normal flow, which works with Gnag, is to push to a feature branch either on a fork or the main repo and once ready I will create a PR. Gnag will execute on the PR created and post any violations directly to that PR irrelevant of the number of commits.

**Comment by amatkivskiy** [comment]
Maybe we are talking about different scenarios.

Let me describe of the scenario that is happening:
1. Create local branch.
2. Commit couple commits.
3. Push the local branch to remote.
4. CI triggers build of this branch (which means executing `gnagCheck`).
5. Create a PR containing changes in your branch. (Unfortunately build triggered in the previous step knows nothing about this PR).
6. CI build finishes with success (meaning no issues found during `gnagCheck`)
7. PR is remains without gnag status and as the result you can't merge it even though checks were successful(because previously gnag status was configured as required)
8. Make another commit and push it.
9. Now CI build is triggered in PR context (which means executing `gnagReport`).
10. Gnag posts successful status and now you can merge PR.

**Comment by stkent** [comment]
Ah, so it sounds like this is because your CI setup only builds on push, not on new PR?

**Comment by amatkivskiy** [comment]
@stkent I am using Circle CI. 
Seems Circle CI builds every commit and then when PR is created github takes the status of the latest commit in it.

**Comment by stkent** [comment]
Is the main repo private and the pull request source a fork of that repository? In that case Circle CI does not build PRs by default:

https://circleci.com/docs/fork-pr-builds/

> If yourorg/yourproject is a public repository, we will run builds for pull requests from otherdev/yourproject under yourorg/yourproject on CircleCI, with some restrictions outlined below.
> 
> If yourorg/yourproject is private, we will not automatically run builds against pull requests from the fork. You can explicitly allow fork PR builds using the advanced feature setting on your-org/your-project at Project settings > Build Settings > Advanced Settings > Project, but it will expose sensitive information to the fork developers.

**Comment by amatkivskiy** [comment]
@stkent No, I am not using forks of the repository but instead commit directly to target private repository. But thanks for pointing the right direction of the possible issue. 

Found this option in Circle CI config:

**Only build pull requests**
> By default, we will build all the commits for this project. Once turned on, we will only build branches that have associated pull requests open. Note: For your default branch, we will always build all commits.

I will turn on it and test how it will work for the project.

**Comment by amatkivskiy** [comment]
Yeah, now gnag works as expected with **Only build pull requests** turned on.

**Comment by btkelly** [comment]
Awesome! Glad to hear it worked out for you @amatkivskiy
