### ISSUE TITLE
Fail gnagReport task if provided Github info is incorrect

### ISSUE THREAD

**Issue by amatkivskiy** [btkelly/gnag#142]
Hi,

It will be very useful if `gnagReport` task fails ASAP when wrong Github info is provided (token, issue number etc.)

Spent some time to fix wrong permissions on Github token because `gnagReport` task doesn't fail when wrong token was provided. Unfortunately `gnagReport` task doesn't really help to track such situations.

I create PR with this fix if you guys don't mind about this.

**Comment by btkelly** [comment]
That's a good catch, more debugging info in the logs and a failure around GitHub communication for the `gnagReport` task would be a nice addition. If you want to create a PR with this change feel free, if not we can add this to our backlog of issues to work on.
