### ISSUE TITLE
Use on a non Android project?

### ISSUE THREAD

**Issue by haarts** [btkelly/gnag#145]
I have a Java project which would benefit from some automatic checking. I've tried using gnag but ran into (obvious) issues. Is it feasible to use gnag on a regular Java (Spring) project?

**Comment by btkelly** [comment]
Gnag is focused on Android but I don't think it would take much to make it work on a plain old Java project. Can you tell me what issues you ran into when attempting to use it on a Spring project? Also any Gradle build log would be helpful with the errors.

**Comment by haarts** [comment]
Most certainly. Just running `/gradlew clean gnagCheck` yields:

```
:clean
:compileJava
:processResources
:classes
:compileTestJava
:processTestResources UP-TO-DATE
:testClasses
:test UP-TO-DATE
:check UP-TO-DATE
:gnagCheck FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':gnagCheck'.
> Could not get unknown property 'android' for root project 'bslegacy' of type org.gradle.api.Project.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 3.168 secs
```

The output of `./gradlew clean gnagCheck --stacktrace --debug` is rather larger, therefor on Sprunge:
stdout: http://sprunge.us/MhSG
stderr: http://sprunge.us/FBIa

**Comment by btkelly** [comment]
Thanks @haarts, I will poke around and see if this is an easy fix to allow Gnag to work with most Java applications.
