### ISSUE TITLE
SuppressWarnings annotation

### ISSUE THREAD

**Issue by haarts** [btkelly/gnag#157]
Call me a fan of Gnag! But sometimes the warnings had a good reason being there. For example in my tests I use lots of 'magic numbers'. Very bad in production code, acceptable in tests (IMHO). Checkstyle is however adamant in complaining:

```
Violation: MagicNumberCheck
Location: src/test/java/eu/someorg/site/SomeTest.java:64
Notes: '123.4' is a magic number.
```

I was hoping to silence these warnings with an annotation on the test method like so:

```java
@SuppressWarnings("checkstyle:magicnumber")
public someTest() { ... }
```

I've cycled through several variants of the annotation but none seem to stick. What's the Right Way?
Also how do I figure out which version of CheckStyle I'm using?

I'm using Gnag 1.3.1.

**Comment by btkelly** [comment]
Glad you're a fan! Thanks for reporting this issue. In quickly glancing at [check style documentation](http://checkstyle.sourceforge.net/config_filters.html#SuppressionCommentFilter) the default check style configuration included with Gnag has this suppression config:

```
<module name="SuppressionCommentFilter">
    <property name="offCommentFormat" value="CHECKSTYLE IGNORE\s+(\S+)" />
    <property name="onCommentFormat" value="CHECKSTYLE END IGNORE\s+(\S+)" />
    <property name="checkFormat" value="$1" />
</module>
```
So something similar to this should work:
```
//CHECKSTYLE IGNORE MagicNumber
public someTest() { ... }
//CHECKSTYLE END IGNORE MagicNumber
```
You can also use the annotation syntax you posted if you modify your check style config to include the newer module like so:
```
<module name="SuppressWarningsFilter" />
<module name="TreeWalker">
   <module name="SuppressWarningsHolder" />
</module>
``` 
I will be working on an update to Gnag to allow the annotation version by default because that looks nicer. I'll post back to this issue once the newer version is released.

**Comment by stkent** [comment]
@btkelly is it possible for Gnag to support both suppression methods simultaneously? Just a thought.

**Comment by btkelly** [comment]
@stkent that's a good idea, I'll run some tests when adding the new annotation style.

**Comment by btkelly** [comment]
Unfortunately I found that the default check style config wont actually work for disabling comments. It is missing the `FileContentsHolder` module which is required for the comment suppression. You can resolve this by adding `<module name="FileContentsHolder" />` as a child of the `<module name="TreeWalker">`. This can be a temporary work around until the next release of Gnag.

**Comment by btkelly** [comment]
@haarts You should be able to update to Gnag 1.3.2 and the inline suppression should work. I've update the `example-android` project's [`ExampleUnitTest.java`](https://github.com/btkelly/gnag/blob/master/example-android/app/src/test/java/com/gnag/example/ExampleUnitTest.java) to show how each works for your exact use case. Let me know if you have any issues.

**Comment by haarts** [comment]
It works! This is why OSS wil win. Many thanks.
