### ISSUE TITLE
Add Kotlin support

### ISSUE THREAD

**Issue by stkent** [btkelly/gnag#161]
Now that Kotlin enjoys first-class support on Android, its usage is likely to increase significantly. Some static analysis tools already exist:

https://github.com/arturbosch/detekt

We should consider adding such tools to Gnag.

**Comment by stkent** [comment]
https://github.com/shyiko/ktlint also looks interesting.

**Comment by stefanomemrise** [comment]
any update on this?

**Comment by stkent** [comment]
That pull request is ready as far as I know; @btkelly has been busy with other things, but he'll be testing the changes as part of starting a new project soon, I believe.

**Comment by stefanomemrise** [comment]
amazing. looking forward to it.

**Comment by stkent** [comment]
(FYI, detekt will be trickier to add than ktlint because ktlint is capable of producing output in checkstyle's report format, whereas detekt seems to use a custom output format at the moment.)

**Comment by stefanomemrise** [comment]
As far as I can see also detekt produces a checkstyle similar report. For example:

```
<?xml version="1.0" encoding="utf-8"?>
<checkstyle version="4.3">
<file name="***Test.kt">
	<error line="133" column="38" severity="warning" message="The more parameters a method has the more complex it is. Long parameter lists are often used to control complex algorithms and violate the Single Responsibility Principle. Prefer methods with short parameter lists." source="detekt.LongParameterList" />
</file>
<file name="***Test.kt">
	<error line="24" column="1" severity="warning" message="Classes with many functions tend to do too many things and often come in conjunction with large classes and can quickly become God classes. Consider extracting methods to (new) classes better matching their responsibility." source="detekt.TooManyFunctions" />
</file>
<file name="***Test.kt">
	<error line="106" column="1" severity="warning" message="Checks whether files end with a line separator." source="detekt.NewLineAtEndOfFile" />
</file>
</checkstyle>
```

**Comment by stkent** [comment]
Oh, nice! That would make adding it a lot easier once 2.0.0 is available :D

**Comment by stkent** [comment]
@stefanomemrise ktlint support is now available; please try out Gnag 2.0.0 and let us know how it works for you!

**Comment by stefanomemrise** [comment]
@stkent thanks I will! - any luck with detekt?

**Comment by stkent** [comment]
I added issue #170 to try detekt integration out soon :)

**Comment by stefanomemrise** [comment]
amazing! thanks.
