### ISSUE TITLE
Android Studio plugin

### ISSUE THREAD

**Issue by ajsb85** [btkelly/gnag#163]
Offers a fully-integrated user experience in Android Studio.

Examples:

- http://www.sonarlint.org/eclipse/
- http://www.sonarlint.org/intellij/

**Comment by btkelly** [comment]
This is really cool! I would love to see a Gnag integration into Android Studio. I'll keep the issue open but I'm not sure I have the bandwidth for this at the moment. If anyone else would like to help with this it would be great.
