### ISSUE TITLE
gnagReport FAILED: Reason: 401 Unauthorized

### ISSUE THREAD

**Issue by ajsb85** [btkelly/gnag#164]
```sh
:name:gnagReport FAILED
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':name:gnagReport'.
> Failed to fetch PR details. Reason: 401 Unauthorized
```

**Comment by btkelly** [comment]
That error usually indicates that the `authToken` you have supplied to Gnag does not have access to the repository you are attempting to use Gnag on. Have you made sure the user that was logged in to get the auth token has the correct permissions for that repo?

Also, could you rebuild the application with the `--stacktrace` flag and post the failure log of that?

Thanks

**Comment by ajsb85** [comment]
I am running here the command:

https://travis-ci.org/flyve-mdm/flyve-mdm-android-inventory/builds/243771041

I updated the token and I am triying just now here:

https://github.com/flyve-mdm/flyve-mdm-android-inventory/pull/3

**Comment by ajsb85** [comment]
Already changed many times the token, I revoke and  re generate the token and the error persist

**Comment by btkelly** [comment]
Ah, I see. Unfortunately Travis CI does not allow environment variable injection on pull requests that come from a forked repository which means the token is null at build time. You can read more about this here https://docs.travis-ci.com/user/pull-requests/ under the section **Pull Requests and Security Restrictions**. I would really like to find a way around this but I don't think there is without getting Travis to change their implementation of the pull request builder. If the pull request comes from the same repository but on a feature branch everything should work as expected.

**Comment by btkelly** [comment]
A private Jenkins instance or possibly other CI systems may allow you to inject values during PR builds. If you find an alternative system I would love to hear about it and add it to the documentation.

**Comment by ajsb85** [comment]
Many options: the first easy, store the token by your side.
And Travis CI can send to you a notification to run the reviewer.

```
notifications:
  webhooks: https://gnag.herokuapp.com/travis_webhook
```

**Comment by ajsb85** [comment]
Create a GitHub App (Integration) with the Pull Request permissions.

**Comment by ajsb85** [comment]
![imagen](https://user-images.githubusercontent.com/663460/27240046-9da514c6-52d3-11e7-8e30-697ffa63f937.png)
