### ISSUE TITLE
Provide a way to specify the version of ktlint

### ISSUE THREAD

**Issue by bmunzenb** [btkelly/gnag#180]
[ktlint](https://github.com/shyiko/ktlint) appears to be locked to an older version in the [source code](https://github.com/btkelly/gnag/blob/master/plugin/src/main/groovy/com/btkelly/gnag/GnagPlugin.groovy#L38).  Is there an easy way to override this?

**Comment by stkent** [comment]
@bmunzenb relevant and recent comment r.e. the tradeoffs of allowing this: https://github.com/btkelly/gnag/issues/174#issuecomment-403527482

**Comment by stkent** [comment]
Maybe we could set a default but allow overrides as a best-of-both-worlds scenario 🤔

**Comment by amatkivskiy** [comment]
@stkent Hi, I am also facing issue related to the ktlint static dependency version.

**Comment by stkent** [comment]
Feedback welcome on #188!

**Comment by stkent** [comment]
This change shipped with v2.1.1. Closing this issue out and making a new one to consider doing the same for other embedded checkers.
