### ISSUE TITLE
Kotlin dsl inconsistency

### ISSUE THREAD

**Issue by andrewgiang** [btkelly/gnag#190]
GnagPluginExtension has isEnabled and setEnabled methods. This allows us to use kotlin properties in the kotlin dsl.

```
gnag{
  isEnabled = true
}
```

ReporterExtension uses isEnabled and enabled. This requires us to use the enabled(bool) method instead of kotlin properties to set the enabled value

```
gnag{
    findbugs {
        enabled(true)
        reporterConfig(project.file("config/findbugs.xml"))
    }
}

**Comment by stkent** [comment]
Is one generally preferred over the other? The assignment version feels more natural in this instance, but could the same argument be made for e.g. the reportConfig method call?

**Comment by andrewgiang** [comment]
Not sure if there is a standard since this is interop code, but I would prefer assignments over using the method calls.
