### ISSUE TITLE
Running gnagReport with `failOnError true` doesn't fail Jenkins builds

### ISSUE THREAD

**Issue by ctrevarthen** [btkelly/gnag#212]
### Steps to reproduce:

1. Update the `gnag` task in `build.gradle` to include `failOnError true`:

```
gnag {
	failOnError true
	detekt {
		enabled true
		reporterConfig(project.file("detekt.yml"))
	}
	github {
		repoName("myrepo")
		setCommentOnSuccess(false)
	}
}
```

2. Edit your project to include a intentional code violation
3. Run `./gradlew clean gnagCheck` locally
4. Observe that the build fails
5. In a Jenkins PR job, set up a Gradle wrapper script to run:
```
gnagReport
-PissueNumber="${ghprbPullId}"
-PauthToken="${GNAG_AUTH_TOKEN}"
```
    NOTE: This will run `gnagCheck` behind the scenes
6. Create a new Github pull request with your intentional code violation
7. Run the Jenkins PR job
8. Observe that the Jenkins jobs builds and succeeds.
9. Observe that the Github PR has a comment from gnag about the code violation

### Expected Behavior:

The Jenkins job *FAILS* when `failOnError` is `true` for gnag and there is a code violation.
The Github PR should still have a comment about the code violation.

**Comment by btkelly** [comment]
Fixed in version 2.2.3
