### ISSUE TITLE
Update default PMD ruleset to use new format

### ISSUE THREAD

**Issue by stkent** [btkelly/gnag#214]
In version 6.X, PMD deprecated their old system of rule grouping ("rulesets") in favor of a new system ("categories"). Support for configuration files that reference rulesets will be removed in PMD 7.X. We should update our configuration files now so that we may use PMD 7 when it releases.

To perform this update, we must first decide whether to prioritize backwards compatibility for consumers, or clarity of configuration file and automatic inclusion of new PMD rules.

- If prioritizing backwards compatibility, we should run a tool like https://github.com/asarkar/pmd-migration-tool that scans all the old rulesets, pulls all the individual rules out of them, and creates a configuration file that references rules one-by-one by name. Gnag users would not need to make any changes in their codebase as a result of this type of change.
- If prioritizing clarity and automatic inclusion of new PMD rules, we should include all new categories by default, then exclude the same rules as are excluded in the current configuration. This may result in a few rules being inadvertently changed (see e.g. https://github.com/pmd/pmd/issues/805#issuecomment-399794689, which references older category-based version of the migration tool from the previous bullet point) for Gnag users. However, note that since our existing default PMD configuration uses rulesets, and rulesets themselves have been subject to change whenever we've updated the PMD version used by Gnag internally, this would not be inconsistent with past Gnag behavior, and would also make it much easier for Gnag users to discover newly-added PMD rules (when a Gnag update surfaces new errors in their codebase).

@btkelly which direction do you prefer here?

**Comment by btkelly** [comment]
I like going with the automatic inclusion of new rules. With the original goal of Gnag being to make inclusion of multiple reporters I think going this route continues with that direction. It might be a bit of a pain when people update but they will always have the ability to customize if they want and it might be good to find new rule violations.

**Comment by stkent** [comment]
Roger that, I'll work on this today!
