### ISSUE TITLE
Update CONTRIBUTING.md to reference one of the available test tasks

### ISSUE THREAD

**Issue by Janani-Subbiah** [btkelly/gnag#223]
Currently the CONTRIBUTING.md doc mentions that we use `./buildAndRunExample.sh` as a way to test and verify changes made to gnag. 
But that task does not exist and maybe we need to update those references to reference all/one of the tasks available (one of the `buildAndRun*.sh` commands).

**Comment by stkent** [comment]
I'll take care of this right now!
