### ISSUE TITLE
Gradle Plugin: support Gradle 7.0

### ISSUE THREAD

**Issue by nailshaykhraziev** [btkelly/gnag#238]
The Gnag Plugin does not work with Gradle 7.0, see logs:

```
FAILURE: Build failed with an exception.

* What went wrong:
A problem was found with the configuration of task ':app:gnagCheck' (type 'GnagCheckTask').
  - Type 'com.btkelly.gnag.tasks.GnagCheckTask' property 'logger' is missing an input or output annotation.
    
    Reason: A property without annotation isn't considered during up-to-date checking.
    
    Possible solutions:
      1. Add an input or output annotation.
      2. Mark it as @Internal.
    
    Please refer to https://docs.gradle.org/7.0.2/userguide/validation_problems.html#missing_annotation for more details about this problem

**Comment by btkelly** [comment]
Thanks @nailshaykhraziev ! I'll be working on updating Gang with Gradle 7 support as well as moving it off of Jcenter. I'll post here once a new version with the issues resolved is available.

**Comment by btkelly** [comment]
@nailshaykhraziev Gradle 7 support has been released, version 7.1.1 is actually the new minimum. If you wanted to give version `3.0.2` a try you should be all set. If you have any issues still please let me know. This was a major version change and you can check out the major changes in the [release notes](https://github.com/btkelly/gnag/releases/tag/v3.0.0) for version `3.0.0`. I would recommend using `3.0.2` though as I fixed / updated a few issues as well as bumping down the JDK requirement to 11 instead of 12.

**Comment by nailshaykhraziev** [comment]
@btkelly Amazing!!!! Thanks for quick helping. Tomorrow, I will try to migrate to new major version.

**Comment by nailshaykhraziev** [comment]
Hi @btkelly 

Now I testing new release and have one problem: 

```
A problem occurred configuring root project 'project_name'.
> Could not get unknown property 'sourceSets' for root project 'project_name' of type org.gradle.api.Project.
Caused by: groovy.lang.MissingPropertyException: Could not get unknown property 'sourceSets' for root project 'project_name' of type org.gradle.api.Project.
	at org.gradle.internal.metaobject.AbstractDynamicObject.getMissingProperty(AbstractDynamicObject.java:85)
	at org.gradle.internal.metaobject.AbstractDynamicObject.getProperty(AbstractDynamicObject.java:62)
	at org.gradle.api.internal.project.DefaultProject_Decorated.getProperty(Unknown Source)
	at com.btkelly.gnag.utils.ProjectHelper.getSourceFilesWithSuffices(ProjectHelper.groovy:85)
```

I added only one new line on the build.gradle (project level):
```
plugins {
    id "com.btkelly.gnag" version "3.0.2"
}
```

After I tried different versions of applying plugin on the build.gradle(app level)(and I try without applying). I think version with 
`apply plugin: 'com.btkelly.gnag'` should be right, but it's not works too((( Maybe you have some ideas for fix current issue. 

Thanks,
Nail

**Comment by btkelly** [comment]
Are you applying this to a multi module project? That error could occur if you are applying the Gnag plugin to the root Gradle file that doesn't have source files of it's own. If this is the case, you can try the instructions for this configuration in the README [here](https://github.com/btkelly/gnag#multi-module-projects). If this doesn't resolve the issue feel free to share all your project Gradle files and I can take a look.
