### ISSUE TITLE
Add markdown util to remove duplicate formatting code

### ISSUE THREAD

**Issue by btkelly** [btkelly/gnag#28]

**Comment by stkent** [comment]
"HTML util" now?

**Comment by btkelly** [comment]
Suppose that makes sense

**Comment by stkent** [comment]
Happy to pick this up when your big restructure is done.

**Comment by stkent** [comment]
@btkelly safe to pick this up?

**Comment by btkelly** [comment]
Yup, go for it @stkent

**Comment by stkent** [comment]
![trolloleopard](https://cloud.githubusercontent.com/assets/6463980/12982780/4d805534-d0b4-11e5-88cd-9c28d008caab.jpg)
