### ISSUE TITLE
Double reports?

### ISSUE THREAD

**Issue by stkent** [btkelly/gnag#49]
I recently [opened a PR](https://github.com/stkent/bugshaker-android/pull/56) and edited the description while the original Travis build was running. gnag commented on the PR twice:

<img width="787" alt="screen shot 2016-01-24 at 3 53 11 pm" src="https://cloud.githubusercontent.com/assets/6463980/12538857/d2b31878-c2b2-11e5-9c81-9a2cc0bd0a4f.png">

Not sure if Travis issue, or gnag issue...

**Comment by btkelly** [comment]
I'm not sure. Did you check if two Travis builds were triggered? This could also happen if you have two different modules that run Gnag. Maybe we should think about how to handle that case, unsure.

**Comment by stkent** [comment]
I tried checking Travis, didn't see an obvious second build. Maybe we could have Gnag report the Travis build number in comments, or include a link back to the Travis job? Could be configurable to be CI-system-agnostic, of course.

**Comment by btkelly** [comment]
Hmm I'm going to close this for now as I'm thinking this was a travis issue. If it comes up again we can revisit.

**Comment by stkent** [comment]
Good call!

![bitmoji](https://render.bitstrips.com/v2/cpanel/9669931-120874784_3-s1-v1.png?palette=1&width=246)
