### ISSUE TITLE
Fix checkAndReport failure Github status

### ISSUE THREAD

**Issue by btkelly** [btkelly/gnag#60]
There seems to be a regression in the checkAndReport task where the failure status is not being set correctly on a PR. A quick fix was to throw a `GradleException` to fail the build but a Github status of failure would be more appropriate. This was working at one point and would set the Gnag status on the Github PR to failure.

**Comment by btkelly** [comment]
This is still an issue, I'm thinking it's related to the user token when running on Travis. Mainly because when testing from my local machine everything works as expected. I would like to look a bit more into the GitHub status API. I'm thinking this might need to be a service that a repo adds in the services section like Travis itself. I'm hoping this would allow the removal of the need for a token all together. Needs some investigating.

**Comment by btkelly** [comment]
Currently working on a companion website to allow users to give Gnag access to their repos which would allow status posting. I'll post status updates here as it progresses.

**Comment by stkent** [comment]
![bitmoji](https://render.bitstrips.com/v2/cpanel/10117671-120874784_5-s1-v1.png?palette=1&width=246)

**Comment by btkelly** [comment]
Unfortunately we have discovered that OAuth applications on GitHub are not allowed to post comments. This is currently a limitation of the GitHub API and unless it is changed by them it wont be possible. The website http://gnag.watch is up and can be used as a helper to get started using Gnag and explains how to add encrypted variables to your Travis config. Closing this issue for now.
