### ISSUE TITLE
Markdown formatting applied to SCREAMING_SNAKE_CASE text?

### ISSUE THREAD

**Issue by stkent** [btkelly/gnag#69]
I saw a recent local report with this comment:

<img width="435" alt="screen shot 2016-03-21 at 8 40 17 pm" src="https://cloud.githubusercontent.com/assets/6463980/13938793/7f02b830-efa5-11e5-8ac0-1e23e9e895b2.png">

The violation is of type [URF_UNREAD_FIELD](http://findbugs.sourceforge.net/bugDescriptions.html#URF_UNREAD_FIELD). It appears that the underscores in this string are being interpreted as emphasis markers in markdown parsing somewhere.

**Comment by stkent** [comment]
Closed because all formatting is via html now?

**Comment by btkelly** [comment]
I guess, I couldn't reproduce the issue.

**Comment by stkent** [comment]
Well if there's no markdown processing left, this definitely can't happen ;)
