### ISSUE TITLE
Parse and linkify URLs in Android lint comments

### ISSUE THREAD

**Issue by stkent** [btkelly/gnag#74]
Example comment for an AllowBackup violation:

> Notes: On SDK version 23 and up, your app data will be automatically backed up and restored on app install. Consider adding the attribute `android:fullBackupContent` to specify an `@xml` resource which configures which files to backup. More info: https://developer.android.com/preview/backup/index.html

The URL is not linkified in reports. It could be!

**Comment by btkelly** [comment]
Interesting, I didn't know links were included in the linter comments. Good find.

**Comment by stkent** [comment]
May be useful: http://stackoverflow.com/questions/285619/how-to-detect-the-presence-of-url-in-a-string

**Comment by stkent** [comment]
http://www.question-defense.com/2010/02/12/include-underscores-while-using-markdown-without-them-being-bold-or-italic-indicators-for-text
