### ISSUE TITLE
[1.1] Findbugs violation detector not mapping URF_UNREAD_PUBLIC_OR_PROTECTED_FIELD violations to correct location?

### ISSUE THREAD

**Issue by stkent** [btkelly/gnag#98]

**Comment by stkent** [comment]
The following `BugInstance`:

``` xml
  <BugInstance type="URF_UNREAD_PUBLIC_OR_PROTECTED_FIELD" priority="2" rank="18" abbrev="UrF" category="STYLE" instanceHash="2fcfb2b9fcff627cf2cd9c44d471b49e" instanceOccurrenceNum="0" instanceOccurrenceMax="0">
    <ShortMessage>Unread public/protected field</ShortMessage>
    <LongMessage>Unread public/protected field: com.detroitlabs.herbie.views.LoginActivity.emailAddress</LongMessage>
    <Class classname="com.detroitlabs.herbie.views.LoginActivity" primary="true">
      <SourceLine classname="com.detroitlabs.herbie.views.LoginActivity" start="21" end="55" sourcefile="LoginActivity.java" sourcepath="com/detroitlabs/herbie/views/LoginActivity.java">
        <Message>At LoginActivity.java:[lines 21-55]</Message>
      </SourceLine>
      <Message>In class com.detroitlabs.herbie.views.LoginActivity</Message>
    </Class>
    <Field classname="com.detroitlabs.herbie.views.LoginActivity" name="emailAddress" signature="Landroid/widget/EditText;" isStatic="false" primary="true">
      <SourceLine classname="com.detroitlabs.herbie.views.LoginActivity" sourcefile="LoginActivity.java" sourcepath="com/detroitlabs/herbie/views/LoginActivity.java">
        <Message>In LoginActivity.java</Message>
      </SourceLine>
      <Message>Field com.detroitlabs.herbie.views.LoginActivity.emailAddress</Message>
    </Field>
    <SourceLine classname="com.detroitlabs.herbie.views.LoginActivity$$ViewBinder$InnerUnbinder" primary="true" start="29" end="29" startBytecode="24" endBytecode="24" sourcefile="LoginActivity$$ViewBinder.java" sourcepath="com/detroitlabs/herbie/views/LoginActivity$$ViewBinder.java">
      <Message>At LoginActivity$$ViewBinder.java:[line 29]</Message>
    </SourceLine>
  </BugInstance>
```

corresponds to an unread field `emailAddress` declared at line 24 of `LoginActivity.java` and assigned at line 29 of the Butterknife-generated class `LoginActivity$$ViewBinder.java`. Ideally, we would parse the location of this `BugInstance` as: line 24 of `LoginActivity.java`. However, I don't see how this is possible using the given data and structure.

**Comment by stkent** [comment]
I'm going to post this for discussion on the FindBugs issue tracker and see what info it turns up.

**Comment by stkent** [comment]
See issue posted [here](https://sourceforge.net/p/findbugs/bugs/1457/). For now, I'm inclined to call this issue 'blocked' as far as Gnag is concerned.

**Comment by dpoggi** [comment]
@stkent It looks like Gnag is triggering FindBugs to generate the deprecated `findbugs.xml` format. Confusingly, the newer format is `findbugsXml.xml` - I don't know how to set the option from the command-line, but I've configured it with Maven. It's possible the newer format has a cleaner way of representing this.

**Comment by stkent** [comment]
@dpoggi thanks! Do you have a reference on the `findbugs.xml` format being deprecated? We are currently setting `output` to `xml:withMessages`, but I don't see any indication on [this page](http://findbugs.sourceforge.net/manual/anttask.html#d0e1367) that another (newer) format is preferred.

**Comment by stkent** [comment]
(Also we're manually naming that file, it's not a built-in).

**Comment by stkent** [comment]
The issue I posted upstream was rejected without comment. 🤷‍♂️

**Comment by dpoggi** [comment]
FindBugs development is done AFAIK, all the love goes into https://github.com/spotbugs/spotbugs

**Comment by stkent** [comment]
Yeah, e.g. https://news.ycombinator.com/item?id=12885549 🤷‍♂️. Hadn't heard about spotbugs before!

**Comment by dpoggi** [comment]
It's a successor fork with the intent of active maintenance. Unfortunately, they decided to require JDK 9 for running the tooling (╯°□°）╯︵ ┻━┻

EDIT: Spoke too soon, it's 8+ now. Guess somebody talked sense into them.

**Comment by stkent** [comment]
![bitmoji](https://render.bitstrips.com/v2/cpanel/10217375-120874784_12-s1-v1.png?transparent=1&palette=1&width=246)
